-- =========================
-- PERSON
-- =========================
CREATE TABLE Person (
    personId    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstName   VARCHAR(50)  NOT NULL,
    lastName    VARCHAR(50)  NOT NULL,
    dateOfBirth DATE         NOT NULL,
    nationality VARCHAR(50)  NOT NULL,
    email       VARCHAR(100) NOT NULL UNIQUE,
    phoneNumber VARCHAR(20)  NOT NULL,
    CHECK (dateOfBirth < DATE '2027-01-01')
);

-- =========================
-- AGENT
-- =========================
CREATE TABLE Agent (
    agentId        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstName      VARCHAR(50)  NOT NULL,
    lastName       VARCHAR(50)  NOT NULL,
    agencyName     VARCHAR(100),
    licenseNumber  VARCHAR(50)  NOT NULL UNIQUE,
    commissionRate NUMERIC(5,2) NOT NULL CHECK (commissionRate BETWEEN 0 AND 100),
    email          VARCHAR(100) NOT NULL UNIQUE,
    phoneNumber    VARCHAR(20)  NOT NULL
);

-- =========================
-- CLUB
-- =========================
CREATE TABLE Club (
    clubId          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clubName        VARCHAR(100) NOT NULL,
    stadiumName     VARCHAR(100) NOT NULL,
    stadiumCapacity INTEGER      NOT NULL CHECK (stadiumCapacity > 0),
    city            VARCHAR(50)  NOT NULL,
    country         VARCHAR(50)  NOT NULL,
    transferBudget  NUMERIC(15,2) NOT NULL CHECK (transferBudget >= 0),
    yearFounded     INTEGER      NOT NULL CHECK (yearFounded BETWEEN 1800 AND 2100)
);

-- =========================
-- SPONSOR
-- =========================
CREATE TABLE Sponsor (
    sponsorId    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sponsorName  VARCHAR(100) NOT NULL,
    industry     VARCHAR(50)  NOT NULL,
    hqCountry    VARCHAR(50)  NOT NULL,
    contactEmail VARCHAR(100) NOT NULL UNIQUE,
    contactPhone VARCHAR(20)  NOT NULL,
    website      VARCHAR(200)
);

-- =========================
-- COMPETITION
-- =========================
CREATE TABLE Competition (
    compId         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compName       VARCHAR(100) NOT NULL,
    compType       VARCHAR(20)  NOT NULL CHECK (compType IN ('League','Cup','Continental')),
    country        VARCHAR(50),
    prizePool      NUMERIC(15,2) CHECK (prizePool IS NULL OR prizePool >= 0),
    organizingBody VARCHAR(100) NOT NULL,
    ranking        INTEGER
);

-- SUBCLASSES
-- =========================
-- PLAYER
-- =========================
CREATE TABLE Player (
    personId        INTEGER PRIMARY KEY,
    primaryPosition VARCHAR(20) NOT NULL CHECK (primaryPosition IN ('GK','DEF','MID','FWD')),
    preferredFoot   VARCHAR(10) NOT NULL CHECK (preferredFoot IN ('Left','Right','Both')),
    marketValue     NUMERIC(15,2) NOT NULL,
    jerseyNumber    INTEGER NOT NULL CHECK (jerseyNumber BETWEEN 1 AND 99),
    height          NUMERIC(5,2) NOT NULL,
    weight          NUMERIC(5,2) NOT NULL,
    FOREIGN KEY (personId) REFERENCES Person(personId) ON DELETE CASCADE
);

-- =========================
-- MANAGER
-- =========================
CREATE TABLE Manager (
    personId           INTEGER PRIMARY KEY,
    clubId             INTEGER UNIQUE,
    coachingLicense    VARCHAR(50) NOT NULL,
    preferredFormation VARCHAR(10) NOT NULL,
    yearsOfExperience  INTEGER NOT NULL CHECK (yearsOfExperience >= 0),
    FOREIGN KEY (personId) REFERENCES Person(personId) ON DELETE CASCADE,
    FOREIGN KEY (clubId) REFERENCES Club(clubId) ON DELETE SET NULL
);

CREATE TABLE Contract (
    contractId     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    personId       INTEGER NOT NULL,
    startDate      DATE NOT NULL,
    endDate        DATE NOT NULL,
    signingDate    DATE NOT NULL,
    contractStatus VARCHAR(20) NOT NULL
        CHECK (contractStatus IN ('Active','Expired','Terminated')),
    FOREIGN KEY (personId) REFERENCES Person(personId) ON DELETE CASCADE,
    CHECK (endDate > startDate),
    CHECK (signingDate <= startDate)
);

CREATE TABLE EmploymentContract (
    contractId       INTEGER PRIMARY KEY,
    clubId           INTEGER NOT NULL,
    weeklySalary     NUMERIC(12,2) NOT NULL CHECK (weeklySalary > 0),
    releaseClause    NUMERIC(15,2),
    signingBonus     NUMERIC(15,2),
    performanceBonus NUMERIC(15,2),
    FOREIGN KEY (contractId) REFERENCES Contract(contractId) ON DELETE CASCADE,
    FOREIGN KEY (clubId) REFERENCES Club(clubId)
);

CREATE TABLE SponsorshipContract (
    contractId       INTEGER PRIMARY KEY,
    sponsorId        INTEGER NOT NULL,
    contractValue    NUMERIC(15,2) NOT NULL CHECK (contractValue > 0),
    paymentFrequency VARCHAR(20) NOT NULL CHECK (paymentFrequency IN ('Monthly','Quarterly','Annual')),
    endorsementType  VARCHAR(50) NOT NULL,
    FOREIGN KEY (contractId) REFERENCES Contract(contractId) ON DELETE CASCADE,
    FOREIGN KEY (sponsorId) REFERENCES Sponsor(sponsorId)
);

CREATE TABLE Transfer (
    transferId    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    personId      INTEGER NOT NULL,
    buyingClubId  INTEGER NOT NULL,
    sellingClubId INTEGER,
    agentId       INTEGER,
    transferFee   NUMERIC(15,2) NOT NULL CHECK (transferFee >= 0),
    transferType  VARCHAR(20) NOT NULL CHECK (transferType IN ('Permanent','Loan','Free')),
    FOREIGN KEY (personId) REFERENCES Person(personId) ON DELETE CASCADE,
    FOREIGN KEY (buyingClubId) REFERENCES Club(clubId),
    FOREIGN KEY (sellingClubId) REFERENCES Club(clubId) ON DELETE SET NULL,
    FOREIGN KEY (agentId) REFERENCES Agent(agentId) ON DELETE SET NULL,
    CHECK (sellingClubId IS NULL OR buyingClubId <> sellingClubId)
);

CREATE TABLE AgentPersonRepresents (
    agentId  INTEGER,
    personId INTEGER,
    PRIMARY KEY (agentId, personId),
    FOREIGN KEY (agentId) REFERENCES Agent(agentId) ON DELETE CASCADE,
    FOREIGN KEY (personId) REFERENCES Person(personId) ON DELETE CASCADE
);

CREATE TABLE CompetitionClubParticipation (
    compId INTEGER,
    clubId INTEGER,
    PRIMARY KEY (compId, clubId),
    FOREIGN KEY (compId) REFERENCES Competition(compId) ON DELETE CASCADE,
    FOREIGN KEY (clubId) REFERENCES Club(clubId) ON DELETE CASCADE
);

CREATE TABLE SponsorClubPartnership (
    sponsorId INTEGER,
    clubId    INTEGER,
    PRIMARY KEY (sponsorId, clubId),
    FOREIGN KEY (sponsorId) REFERENCES Sponsor(sponsorId) ON DELETE CASCADE,
    FOREIGN KEY (clubId) REFERENCES Club(clubId) ON DELETE CASCADE
);